🚀 프로젝트에 checkstyle(lint)과 code style(formatter) 설정
backendoori/ootw-backend pull request #19
Opened 2023-12-21 10:44 UTC by Sehee-Lee-01

## ✅ 요구사항 
### 1. checkstyle(Java Lint) 적용
  - [x] `config/checkstyle/checkstyle.xml` 추가: 기본 스타일인 구글 [google checkstyle](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) 적용 후 커스텀
  - `config/checkstyle/suppressions.xml`  추가: Lint를 조금 더 세밀하게 반영하고 싶지 않을 때. 불필요한 Lint Warning이 있을 때 코드를 작성하는 파일(`checkstyle.xml` 파일과 세트입니당.)
  - `config/checkstyle/configuration_1_3.dtd`과 `config/checkstyle/suppressions_1_2.dtd`: 원래 이 파일은 원본 구글 `checkstyle.xml`, `suppressions.xml`에서 http로 매번 받아와야하는 것 같던데 http 통신 없이 사용할 수 있도록 아예 넣어놨습니다. 
  - `gradle.build`에 플러그인 적용 및 위 두 개 파일 인식하도록 설정
  
### 2. checkstyle을 기반으로 한 intellij code style xml(`.idea/codeStyles/Project.xml`) 생성

  
## 🚀 주요 변경사항

- 기존 모든 소스코드 code style 반영
- 새로 설정된 코드 스타일을 설정하기 위해 pull 이후 code style 설정에서 `Project`를 설정해줘야합니다!(아래 사진 참고)

![image](https://github.com/backendoori/ootw-backend/assets/85275893/9042adb6-77ac-4d3e-af54-3222924065c6)

| **세부 스타일 설정**은 commit log 참고 부탁드립니다!

## 💡 기타사항

### 1. Code Style 설정 방법에 대한 고민을 했습니다.
  - code style 설정 방법에는 두 가지가 있는데 .editorconfig 파일을 이용하는 것과 현재 적용한 것처럼 xml 설정이 있습니다. 
    - intellij code style xml 설정은 인텔리제이 ide에만 한정되고 editorconfig 특정 ide에 구애받지 않는다는 특징이 있습니다.
    - 다만 editorconfig는 플러그인 설치를 별도로 적용해야하는 것으로 알고 있고, 모든 팀원이 인텔리제이를 기본적으로 사용하고 있어서 intellij code style xml로 설정하게 되었습니다!

- ### 추후 생각할 일(참고) 
  - html 파일로 리포트를 받는 설정이 있는데 필요하면 반영해보겠습니다! 
  - maxwarnings 처리를 안한 상태라 경고만 뜨고 빌드에는 영향이 가지 않습니다. 추후 필요하다면 빌드에도 영향이 가도록 바꾸겠습니다!
  - 쿼리 DSL 적용 후 수정이 필요할 수도 있습니다.
  - [메서드 라인 제한](https://checkstyle.sourceforge.io/checks/sizes/methodlength.html#MethodLength) 확인만 해보기 => jacoco 메서드 라인 제한 처럼 여기에도 확인하는 것이 있네용!

2023-12-21 14:03 UTC, ASak1104 requested changes
check style 때문인지 코드 컨벤션이 다른 부분이 있네요!

2023-12-21 14:03 UTC, ASak1104 commented on src/main/java/com/backendoori/ootw/domain/BaseEntity.java
> +import lombok.Getter;
이 부분에서 개행이 들어가는 부분은 수정이 되면 좋겠네요

2023-12-21 14:03 UTC, ASak1104 commented on build.gradle
>  }
이 부분은 indent가 다르네요

2023-12-21 14:30 UTC, shoeone96 commented on src/main/java/com/backendoori/ootw/domain/BaseEntity.java
> +import lombok.Getter;
static이 들어가는 게 기준이 아니라 띄어쓰는 기준이 바뀐 것 같기도 하네요

2023-12-21 14:45 UTC, Sehee-Lee-01 commented on src/main/java/com/backendoori/ootw/domain/BaseEntity.java
> +import lombok.Getter;
헉 죄송합니다,,,, 바로 고쳤습니다....

2023-12-21 14:46 UTC, Sehee-Lee-01 commented on build.gradle
>  }
인텔리제이에서는 괜찮았는데 올리니 바뀌었군요,,, 수정 완료햇습니다! 감사합니다ㅜㅜ

2023-12-21 19:22 UTC, ASak1104 requested changes
고생하셨습니다!
리뷰로 남긴 부분은 같이 검토해보면 좋을 것 같아요!

2023-12-21 19:22 UTC, ASak1104 commented on src/main/java/com/backendoori/ootw/domain/BaseEntity.java
> +import lombok.Getter;
이 부분은 import문의 오더가 다른 것 같아요!
아래와 같이 formatting이 되야할 것 같습니다!

```java
import jakarta.persistence.EntityListeners;
import jakarta.persistence.MappedSuperclass;
import java.time.LocalDateTime;
import lombok.Getter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
```

2023-12-21 19:22 UTC, ASak1104 commented on build.gradle
> +}
이 부분에 필요 없는 공백이 조금 있네요!
아래와 같이 수정하면 좋을 것 같습니다

```suggestion
checkstyle {
    toolVersion = "10.12.5"
    configFile = file("${rootDir}/config/checkstyle/checkstyle.xml")
    configProperties = [
            "org.checkstyle.google.suppressionfilter.config"     : "suppressions.xml",
            "org.checkstyle.google.suppressionxpathfilter.config": "suppressions.xml"]
}
```

2023-12-22 00:15 UTC, Sehee-Lee-01 commented on build.gradle
> +}
잡아 주셔서 감사합니다! 뭔가 줄바꿈 작업을 좀 많이 하다보니 컴퓨터가 제대로 잡질 못하는 것 같네요,,, 윈도우에서는 아래 고친 부분 처럼 보여서 인식을 못하고 있었습니다! 감사합니다ㅠㅠㅠ

2023-12-22 00:15 UTC, Sehee-Lee-01 commented on src/main/java/com/backendoori/ootw/domain/BaseEntity.java
> +import lombok.Getter;
확인해서 방금 고쳤습니다! 바로 커밋 올리겠습니다!

2023-12-22 00:26 UTC, Sehee-Lee-01 commented on build.gradle
> +}
수정이전에는 탭문자가 있었네요! ide 상에서는 스페이스 4개 크기와 동일하게 보이는데 github에서는 크기가 달라서 다르게 보이는 것이었습니다! 스페이스 4개로 수정했습니다~!

2023-12-22 03:03 UTC, merged