Feature ci
backendoori/ootw-backend pull request #21
Opened 2023-12-21 16:04 UTC by shoeone96

## ✅ 요구사항 
- [x] github action CI/CD 구현

## 🚀 주요 변경사항
- MySQL과 spring server build 를 띄워 검증 진행
- 직접 action 안에서 schema를 MySQL에 넣는 방식으로 진행(spring에 불필요한 의존성 추가하지 않음)
- build 및 테스트 종료되는 것 확인
- pull Request를 main branch로 할 때마 action이  진행됨

## 💡 기타사항
- #12  번에 해당하는 내용임
- 추후 로걸 환경에서 돌렸던 docker compose를 github action 안에서 띄우는 방식으로 변경 고려
- lint와 jacoco의 기준에 못미쳤을 시 action 과정이 실패하는지 확인 필요

2023-12-21 16:09 UTC, Sehee-Lee-01 commented
확인했습니다! 너무...너무... 고생하셨습니다...🚀🥲

2023-12-21 18:39 UTC, ASak1104 reviewed
파일 명에 sync 를 추가한 이유가 있을까요?

2023-12-21 18:50 UTC, ASak1104 requested changes
정말 고생하셨습니다 🥺
오류 부분만 수정하고 네이밍만 잠깐 논의하면 merge해도 될 것 같습니다!

2023-12-21 18:50 UTC, ASak1104 commented on .github/workflows/pr_sync_ci.yml
> +        run: mysql -h localhost -P 3306 -u ${{secrets.TEST_DB_USERNAME}} -p${{secrets.TEST_DB_PASSWORD}} --protocol=tcp < ./mysql/schema.sql
해당 job에서 실패하네요 아마도 아래와 같이 바꿔줘야 할 것 같아요! [stackoverflow](https://stackoverflow.com/questions/58222386/github-actions-using-mysql-service-throws-access-denied-for-user-rootlocalh)

```suggestion
      - name: Into Schema
        run: mysql -h 127.0.0.1 -P 3306 -u ${{secrets.TEST_DB_USERNAME}} -p${{secrets.TEST_DB_PASSWORD}} --protocol=tcp < ./mysql/schema.sql
```

2023-12-21 18:50 UTC, ASak1104 commented on .github/workflows/pr_sync_ci.yml
> +      - name: Into Schema
`Into Schema` 라는 이름이 추상적인 느낌이 들기도 하네요 `Execute DDL script`는 어떨까요?
```suggestion
      - name: Execute DDL script
```

2023-12-22 00:46 UTC, Sehee-Lee-01 commented on .github/workflows/pr_sync_ci.yml
> +      - name: Into Schema
Create schema 좋은 것 같습니다!

2023-12-22 01:58 UTC, shoeone96 commented on .github/workflows/pr_sync_ci.yml
> +        run: mysql -h localhost -P 3306 -u ${{secrets.TEST_DB_USERNAME}} -p${{secrets.TEST_DB_PASSWORD}} --protocol=tcp < ./mysql/schema.sql
오 이건 제 개인 repo에서는 성공했었는데 다시 봐야겠네요

2023-12-22 05:29 UTC, shoeone96 commented
현재 secret 적용 문제로 일시적으로 close 합니다.

2023-12-22 05:29 UTC, closed without merging